name: tf_rider
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0
  sms_autofill: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Group 12.svg
    - assets/Group 7.svg
    - assets/Group 8.svg
    - assets/Group 9.svg
    - assets/Sandwich_100px.svg
    - assets/Kawaii Soda_100px.svg
    - assets/Salad_100px.svg
    - assets/Cookie_100px.svg
    - assets/Popcorn_100px.svg
    - assets/Kawaii Ice Cream_100px.svg
    - assets/Kawaii Pizza_100px.svg
    - assets/Steak Hot_100px.svg
    - assets/Kawaii French Fries_100px.svg
    - assets/Welcome to Tasty Food.svg
    - assets/Image 6.svg
    - assets/Image 7.svg
    - assets/Image 8.svg
    - assets/Image 11.svg
    - assets/Image 12.svg
    - assets/Image 13.svg
    - assets/Image 14.svg
    - assets/Image 15.svg
    - assets/Icon awesome-user-circle.svg
    - assets/Icon feather-bell.svg
    - assets/profile.svg
    - assets/Line 18.svg
    - assets/orders.json
    - assets/Group 355.svg
    - assets/Group 2.svg
    - assets/Icon map-food.svg
    - assets/Group 72.svg
    - assets/Group 73.svg
    - assets/Path 73.svg
    - assets/Icon material-history.svg
    - assets/Icon open-account-logout.svg
    - assets/Path 68.svg
    - assets/Group 318.svg
    - assets/Group 319.svg
    - assets/Icon ionic-ios-mail.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
